# Generated by Django 5.0.1 on 2024-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_email_user_password_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
