# Generated by Django 5.0.1 on 2024-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
        ("user", "0007_user_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cars",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to="car.car"
            ),
        ),
    ]
