# Generated by Django 5.0.1 on 2024-02-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
        ("user", "0009_user_is_active_user_is_staff_user_last_login_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserModel",
        ),
    ]
