# Generated by Django 5.0.1 on 2024-02-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
        ("user", "0010_rename_user_usermodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserModel",
            new_name="User",
        ),
    ]
